### ISSUE TITLE
Invalid Read

### ISSUE THREAD

**Issue by npmccallum** [AMDESE/sev-tool#10]
The maximum bound for iteration at the following two locations is incorrect, causing an invalid read.

https://github.com/AMDESE/sev-tool/blob/88ef8c728e26981b805af80cd00fcf556450706c/src/commands.cpp#L756

https://github.com/AMDESE/sev-tool/blob/88ef8c728e26981b805af80cd00fcf556450706c/src/commands.cpp#L760

**Comment by lilienbm** [comment]
Ahh. Will fix Monday (ooo now)

**Comment by lilienbm** [comment]
Fixed 
https://github.com/AMDESE/sev-tool/commit/3e740bb10c9d96f0bb5317ad53079a41ff86e69c
