### ISSUE TITLE
Unused Line in makefile

### ISSUE THREAD

**Issue by lilienbm** [AMDESE/sev-tool#11]
Does anyone know what this line in the makefile is supposed to be doing? I took it out and it still `compiles.

.cc.o: $(CXX) $(CXXFLAGS) -c $(USER_DIR)/$^  ${CPPFLAGS}

**Comment by RARelph** [comment]
Brian,
    That line is the “rule” for converting any .cc file to a .o file. Though I think it’s usually on two lines.
Richard

**Comment by lilienbm** [comment]
I was thinking that is what this middle line is for

SRCS= $(wildcard ${USER_DIR}/*.cpp)
OBJS= $(SRCS:.cpp=.o)
$(OBJS) : $(USER_DIR)/sevapi.h $(USER_DIR)/utilities.h $(SSL_HEADERS)

**Comment by RARelph** [comment]
The OBJS= line just defines a list of file names… For each .cpp file in the SRCS variable (another list of file names, defined on the SRCS= line above), create an equivalent file in the OBJS variable, but with a .o extension instead of .cpp.

**Comment by ldeweysuse** [comment]
Like @RARelph was mentioning, this compiles the `.cpp` and `.h` files in to object files. In the original make file the rule was named `.cc.o:`. It is not `.cpp.o:` in the current Makefile.
