### ISSUE TITLE
Tests folder not created by tool

### ISSUE THREAD

**Issue by mickys** [AMDESE/sev-tool#12]
Let's just say i've spent 2 days thinking the tests are not working on my machine because of this.
**Note that the tool will clear this directly before the tests are run.**

$ sudo ./sevtool --ofolder ./tests --test_all
```
root@Ubuntu-1804-bionic-64-minimal /opt/sev-sevtool/src # ./sevtool --ofolder ./tests --test_all
*Starting factory_reset tests
Error: Set Platform externally owned, failed

Command Unsuccessful: 0x01
```

https://github.com/AMDESE/sev-tool/blob/master/src/tests.cpp#L34 
does indeed clean the --ofolder , 

yet it could actually check if it exists, clear it in that case else create it.

**Comment by lilienbm** [comment]
I remember there was an issue with creating the folder, but I will add a check right now to printf if the folder is not there

**Comment by lilienbm** [comment]
I think the issue with having the tool create the folder was that, because we're running the tool with sudo, it would create the folder with sudo also, which I had some issue with, at one point. 
Although, it would have the same permissions as the files inside, which would also be created with sudo...

**Comment by lilienbm** [comment]
Yep, the tool will create the folder whose owner is root instead of as the user, and that's not what we want

Here's the changeset. It will automatically throw a failure if the folder does not exist
https://github.com/AMDESE/sev-tool/commit/66be87bf24ba35cf439d60b0ea10803791af91db
