### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [AMDESE/sev-tool#17]
I would like to point out that an identifier like “[`__PSP_SEV_USER_H__`](https://github.com/AMDESE/sev-tool/blob/a3647d53947760b9290d2c3fbeef3f2f7bde2cf3/lib/psp-sev.h#L13 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by lilienbm** [comment]
This file was copied from the Linux kernel, so that the project can always reference the newest PSP APIs. I'd suggest getting it changed there
https://github.com/torvalds/linux/blob/master/include/uapi/linux/psp-sev.h

**Comment by elfring** [comment]
* Would you like to reconsider the consequences for the usage of [such a source file](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/psp-sev.h?id=1d57b17c60ff245b8e50813bf0fd24143ecf26d4 "crypto: ccp: Define SEV userspace ioctl and command id") by this tool?
* How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
