### ISSUE TITLE
/dev/sev needed for sevtool commands on Guest Owner?

### ISSUE THREAD

**Issue by alina-weber** [AMDESE/sev-tool#27]
As far as I understood the attestation process, the part of the Guest Owner is supposed to be executed on a different platform possibly not even having AMD SEV. Some commands, like `calc_measurement` need the `/dev/sev` interface, but the Guest Owner has no access to it. In case of `calc_measurement` `/dev/sev` is used while calculating the platform status to determine the API version. I do not understand why this is necessary, as the major and minor API are given as arguments to the command.
I was able to make the command work by initializing the `SEVDevice` object with NULL and commenting the source code lines: `commands.cpp`: 504, 505, 509 and 510 as well as rewriting line 515 with `if(false){`.

**Comment by MidoriYuki** [comment]
Hey,
I tried the commit 06dc9af as well as the current one and in both cases /dev/sev is called while `calc_measurement` and `validate_cert_chain`, because the constructor of Command still wants to get the SEVdevice, sorry I forgot to change the line 32 of commands.cpp to initialize `m_sev_device` with `NULL`. It works then. Though this change would only be viable for the Guest Owner version of sev-tool and not for the Hypervisor. Is it possible to use an additional argument for the configuration to set a macro to initialize `SEVDevice` (hypervisor) or set it to `NULL` (Guest Owner)?

**Comment by lilienbm** [comment]
Hi, please let me know if this fixes your issue https://github.com/AMDESE/sev-tool/commit/0cdd67def0f137c50185f267fa56f3a5c3085a9a

**Comment by MidoriYuki** [comment]
I tested it. So far, the installation on hypervisor and guest owner went flawlessly, thanks for you efforts. 
I tried to execute the attestation process as far as possible. The first part of the hypervisor went as expected and without any issues. 
The first command executed by the guest owner, `validate_cert_chain`, did not work and returned status code: 0x06 which means "invalid certificate" as far as I looked it up in the source code. To test the command, I used an empty folder where I extracted the certificates to and also tested it with a separate folder where I just copied (with scp) the certificates from the hypervisor, but this did not work either. In contrast `validate_cert_chain` was executed successfully on the hypervisor.

**Comment by alina-weber** [comment]
Have there been any updates so far regarding the above issues? Especially regarding 'validate_cert_chain'?

**Comment by lilienbm** [comment]
I believe that's been fixed since Sep 2nd, is it not working? https://github.com/AMDESE/sev-tool/commit/0cdd67def0f137c50185f267fa56f3a5c3085a9a

**Comment by jpecholt** [comment]
The [pull request #33](https://github.com/AMDESE/sev-tool/pull/33) fixes the dependencies to the SEV hardware, meaning you can create launch blobs, validate certificate chains and create the correct packaged secrets without the need of being on the host system itself. I tested it and so far everything is working as intended.

**Comment by lilienbm** [comment]
calc_measurement does not require the CCP driver. If this is still an issue, we can re-open the ticket. But we have also just updated generate_launch_blob and package_secret to also not require the CCP driver.

     Command cmd(output_folder, verbose_flag, CCP_NOT_REQ);
                cmd_ret = cmd.calc_measurement(&user_data);
