### ISSUE TITLE
SEV Remote Attestation vulnerability

### ISSUE THREAD

**Issue by picolens** [AMDESE/sev-tool#28]
Hi

Was curious to know if SEV is still vulnerable to the firmware rollback attacks described in this Sep 2019 paper.

https://arxiv.org/abs/1908.11680

After googling a bit, I was unable to find any mention of it being fixed, or addressed. Though, it's quite possible, probable even, that I'm really bad at searching ;)

Thanks

**Comment by exFalso** [comment]
This is partially addressed with SEV-SNP which introduces a versioned key (VCEK). There are still some things missing, in particular a mechanism by which clients can decide if a version is considered secure or not (https://github.com/AMDESE/AMDSEV/issues/89)

**Comment by larrydewey** [comment]
Closing this issue for now. Feel free to re-open if you feel necessary
