### ISSUE TITLE
Calculation of the LaunchDigest

### ISSUE THREAD

**Issue by alina-weber** [AMDESE/sev-tool#29]
I already posted my question in the related closed issue https://github.com/AMDESE/sev-tool/issues/9#issuecomment-734825453
As that issue is closed I was not sure if you will be notified about it, so here as a fresh issue.

I tried to implement the calculation of the launch digest as explained in https://github.com/AMDESE/sev-tool/issues/9#issuecomment-481713014 . I tested if my calculation is correct via the `calc_measurement` command of the sev-tool, but was not able to achieve a positive result. A more detailed explanation of my implementation can be found here https://github.com/AMDESE/sev-tool/issues/9#issuecomment-734825453. Could you give a more detailed explanation on how to calculate this digest?
 
Is it possible to read the GTCX.LD (launch digest) as hypervisor and if it is possible can you please explain how? This would shorten the process of testing ones implementation.

As far as I understood the attestation process, the launch digest is necessary for the attestation and has to be accessible to the hypervisor so the host can send it to the Guest Owner. The Guest Owner then uses the launch digest to verify the measurement, which is also extracted from the VM by the hypervisor and then sent to the Guest Owner. Is it possible to implement the same functionality (to get the measurement via the QMP monitor) for the launch digest?

**Comment by RARelph** [comment]
[AMD Official Use Only - Internal Distribution Only]

Alina,
    New in SEV 0.23 is the ATTESTATION command, which allows the hypervisor to obtain the same launch measurement that the guest owner gets via the LAUNCH_MEASURE command.
Richard
________________________________

**Comment by alina-weber** [comment]
We currently only have an Epyc Naples processor. For Naples is only a firmware update till version 0.17 available. So I can not call the `ATTESTATION` command. Will a firmware update for Naples to version 0.23 or higher be available in the future?

**Comment by alina-weber** [comment]
Additionally, the Guest Owner should also be able to calculate the launch digest to verify the loaded OVMF file and possibly more. How is the GO supposed to calculate the launch digest?

**Comment by rgentz** [comment]
is there an update here? I have the same issue

**Comment by lilienbm** [comment]
There are no current plans to add the Attestation command to Naples or to move Naples to the 0.23 version of firmware. Rome or Milan will have to be used for those features.
To calculate the launch digest, we recommend using the calculate_measurement sev-tool command. The GO knows what data they are passing in during LaunchUpdateData/VMSA calls, so you can calculate the digest of that data yourself and pass in the parameters you expect to be running on the server (api version, etc. see measurement_t in commands.h) and the tool will output the measurement that can be used to compare against LaunchMeasure

**Comment by rgentz** [comment]
Thank you @lilienbm but I am still not 100% following. (I have a Rome CPU)
I thought the calculate_measurement needs the digest etc as an input?

Let as far as I understand the calc_measurement command need the following inputs. 

Required input args: 
[Context]  = Always 0x04
[Api Major]  = get from ./sevtool --verbose --platform status
[Api Minor]  = get from ./sevtool --verbose --platform status
[Build ID] = get from ./sevtool --verbose --platform status
[Policy] = defined by me e.g to 0x00
 [Digest] = ??Sha384 of my VMimageFile??
[MNonce] = ??get from ./sevtool --verbose  --ofolder ./certs --generate_launch_blob 0
[TIK] = get from ./sevtool --verbose  --ofolder ./certs --generate_launch_blob 0


if it helps this is how I start the VM. Let me know if this is wrong in the first place
```
sudo virt-install \
               --name sev-guest \
               --memory 4096 \
               --memtune hard_limit=4563402 \
               --boot uefi \
               --disk /var/lib/libvirt/images/sev-guest.img,device=disk,bus=scsi \
               --disk /var/lib/libvirt/images/sev-guest-cloud-config.iso,device=cdrom \
               --os-type linux \
               --os-variant ubuntu20.04 \
               --import \
               --controller type=scsi,model=virtio-scsi,driver.iommu=on \
               --controller type=virtio-serial,driver.iommu=on \
               --network network=default,model=virtio,driver.iommu=on \
               --memballoon driver.iommu=on \
               --graphics none \
               --launchSecurity type=sev,cbitpos=47,reducedPhysBits=1,policy=0x0000,dhCert=certs/godh.base64,session=certs/launch_blob.base64
```

**Comment by rgentz** [comment]
Could you give this a quick look if this is correct?

**Comment by lilienbm** [comment]
I can't comment on any qemu settings; I work on SEV firmware, not the OS side. The digest is the SHA of every page you pass into LaunchUpdateData/VMSA. So in OpenSSL, you can call SHA256_Update on all of the pages you're passing into the firmware.

SHA256_Init(&mLaunchDigestCTX);
for(each page you call LaunchUpdate)
        SHA256_Update(&mLaunchDigestCTX, Data.Addr(), Data.Size());
uint8_t Digest[SHA256_DIGEST_LENGTH] = {0};
SHA256_Final(Digest, &mLaunchDigestCTX)

**Comment by rgentz** [comment]
Thank you @lilienbm for your reply. Could you point me to a resource for the OS side?

**Comment by its-luca** [comment]
@rgentz 
To my understanding, qemu calls launch_update on  the first "pflash" device [1] .
In the official launch script this is done via   
`-drive if=pflash,format=raw,unit=0,file=${UEFI_CODE},readonly` where `UEFI_CODE` holds the path to `OVMF_CODE.fd`. 
I also found it helpful to add some printks to the kernel code, to see which data gets launched [2]. 
Finally, James Bottomley has created a python script for the attestation process [3].

Hope this helps.




[1] https://github.com/qemu/qemu/blob/d45a5270d075ea589f0b0ddcf963a5fea1f500ac/hw/i386/pc_sysfw.c#L303

[2] https://github.com/torvalds/linux/blob/77d34a4683b053108ecd466cc7c4193b45805528/arch/x86/kvm/svm/sev.c#L485

[3] https://blog.hansenpartnership.com/wp-uploads/2020/12/sevsecret.txt

**Comment by larrydewey** [comment]
@rgentz this issue thread seems to be quite old, so I will close it for now. If your issue hasn't been resolved, feel free to re-open it, and we would be happy to address this further.

**Comment by vamanea** [comment]
Sorry to add extra comments, but perhaps it can help others trying to understand this.

I was also trying to calculate the reference hash manually and this is how I managed to get the same hash as LAUNCH_MEASURE on a SEV-ES platform.

My solution assumes you will only run UPDATE_VMSA at the end, just before LAUNCH_MEASURE.

Just like @lilienbm mentioned, I followed the same route:
```
SHA256_Init(&mLaunchDigestCTX);
for(each page you call LaunchUpdate)
  SHA256_Update(&mLaunchDigestCTX, Data.Addr(), Data.Size());
```

However when UPDATE_VMSA is called the hash will be updated with the data from the VMCB area, but the VMCB area is only available to the kernel - it's impossible to calculate the final hash from userspace . For my test software I just did the lazy thing of dumping the VMCB to kernel log when UPDATE_VMSA is called.
I added something like this in sev.c, in  __sev_launch_update_vmsa(), a very crude solution but it was mostly for testing:
```
pr_info("Update VMSA\n");
print_hex_dump_bytes("vmsa: ", DUMP_PREFIX_ADDRESS, svm->sev_es.vmsa, PAGE_SIZE);
```

After I update the hash
```
SHA256_Update(&mLaunchDigestCTX, vm->sev_es.vmsa, PAGE_SIZE);
```
and call get the hash:
```
uint8_t Digest[SHA256_DIGEST_LENGTH] = {0};
*SHA256_Final(Digest, &mLaunchDigestCTX)
```

and now the my HMAC matches the one from SEV. You can also verify this by running the ATTESTATON command, which will return the exact HASH(not HMAC!) of the guest.
