### ISSUE TITLE
sev-tool doesn't reseed the random number generator

### ISSUE THREAD

**Issue by jejb** [AMDESE/sev-tool#30]
This means that on first run, the same "random" nonce and keys are produced over and over.  You can verify by doing

sevtool --generate_launch_blob
xxd tmp_tk.bin
sevtool --generate_launch_blob
xxd tmp_tk.bin

The two outputs will be identical because the rand() call has the same default seed for each invocation.  This should be fixed either by randomly seeding rand() or using a random number generator directly attached to the system entropy, like getrandom()

**Comment by lilienbm** [comment]
this was fixed in https://github.com/AMDESE/sev-tool/commit/eba5d419cb0b813b0b2decbb57878a9ee7cb4519#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26
