### ISSUE TITLE
Pull-Request Format

### ISSUE THREAD

**Issue by jpecholt** [AMDESE/sev-tool#32]
Hi,

I've been modifying the code for the last couple of days to:
- fix some bugs (e.g. validate_cert_chain being dependent on SEV hardware)
- improve some commands and functions (e.g. checking the usage/algo flags of parent key and child signature during certificate verification) 
- implement new features (e.g. sign_pek_csr which signs the previously exported CSR and creates the oca.cert in the correct format) 
- modify existing commands (e.g. pek_cert_import which now imports the previously signed CSR together with the oca.cert instead of performing these steps as well) and
- update and improve the Readme (e.g. I explained calc_measurement in more detail and added sign_pek_csr).

All my changes have been tested (I created a new test case for sign_pek_csr) and I managed to run your Use Case with GO and PO being on different systems each, where the PO is the only entity with SEV hardware, which was not previously possible. Additionally, the OCA private key does not need to be located on the PO server anymore, signing the PEK_CSR can be performed on an external system. I have not been the best at committing in small steps, unfortunately, and instead have a few massive commits which cover a bit of everything.  
Therefore I was wondering what format you prefer for pull-requests?  Naturally, I can modify the commit messages to reflect the changes more closesly, but splitting the commits up will be a bit more complex, which is why I wanted to ask you about your requirements first.

Cheers,
Jo

**Comment by lilienbm** [comment]
Hi Jo, let's start with a pull request and see if that's easy enough.

**Comment by jpecholt** [comment]
Thanks!
