### ISSUE TITLE
Sign PEK with OCA

### ISSUE THREAD

**Issue by khushboo-dfn** [AMDESE/sev-tool#42]
> You have to run this on an AMD platform that supports SEV. You generated the certificate correctly, but Error code 0x1 (as found in the SEV API https://www.amd.com/system/files/TechDocs/55766_SEV-KM_API_Specification.pdf) is INVALID_PLATFORM_STATE. This probably means either you are not running on an SEV-supported platform or your OS does not support the ccp kernel driver.

_Originally posted by @lilienbm in https://github.com/AMDESE/sev-tool/issues/39#issuecomment-852528329_

I am trying to follow through the tutorial and when I run the following command, I am seeing the INVALID_PLATFORM_STATE error:
```
khushboo@sev:~/sev-tool/src$ sudo ./sevtool --verbose --pek_cert_import ./certs/ec384-key-pair.pem 

Command Unsuccessful: 0x01
```
Looking at @lilienbm's comment, I checked to make sure that my platform supports SEV and it does:
```
khushboo@sev:~/sev-tool/src$ dmesg | grep SEV
[   23.288345] ccp 0000:22:00.1: SEV API:0.22 build:13
[   24.230238] SVM: SEV supported
```
Not sure what I am doing wrong. Would appreciate some help.

**Comment by RARelph** [comment]
The pek_cert_import command is only valid when the platform is self-owned. There are a number of other constraints, but I suspect that's the one that is tripping you up. What do you get back from platform_status?

**Comment by khushboo-dfn** [comment]
```
khushboo@sev:~/sev-tool/src$ sudo ./sevtool --verbose --platform_status
api_major:	0
api_minor:	22
platform_state:	2
owner:		0
config:		0
build:		13
guest_count:	1

Command Successful
```

**Comment by RARelph** [comment]
Yes, the platform is self-owned... but you have an active guest. You can only change the ownership if the platform is in the UNINIT state. I think sev-tool and the driver will cooperate to get you to UNINIT state... but ONLY if there are no guests running.

**Comment by khushboo-dfn** [comment]
Ah that's helpful. I will try to get that going.

**Comment by khushboo-dfn** [comment]
Removing the guest worked for me. Thanks a bunch! Closing this issue.
