### ISSUE TITLE
SEV INIT error 0x13

### ISSUE THREAD

**Issue by IceCY** [AMDESE/sev-tool#43]
Hi, everyone.

When I follow the guideline in the "OS Requirements for Platform Owners" part,  I got the following output:
```
[    6.066387] ccp 0000:42:00.1: SEV: failed to INIT error 0x13
```
I checked linux source code that `0x13` represents  `SEV_RET_HWSEV_RET_PLATFORM` (hardware error). But I don't know what it means and how it can be fixed.

Do you have any ideas ?

System Configuration: 
```
CPU:  
         AMD EPYC 7313 16-Core Processor
UEFI version:             
         6.10 (Build ID: CFE126V)
UEFI Copyright:  
         Version 2.21.1280
         Copyright(c) 2021 American Megatrends, Inc.
PSP Bootloader Version:      
         0.13.0.50     

OS: 
         Ubuntu 20.04.2 LTS (Linux 5.8.0-43-generic)
```

**Comment by lilienbm** [comment]
Make sure SMEE is specifically set to Enabled in the BIOS CBS options

**Comment by IceCY** [comment]
Thanks a lot. It solves my problem.
