### ISSUE TITLE
Calculation of the measurement is not correct on Rome

### ISSUE THREAD

**Issue by zeyu-zh** [AMDESE/sev-tool#44]
The OVMF digest on Rome should be the format of SHA384. However, the struct measurement_t expects SHA256_DIGEST_LENGTH.

Furthermore, It would be great if the developer could test the remote attestation on Rome with this tool, and post the whole operation flows, especially the measurement calculation.

**Comment by zeyu-zh** [comment]
Another question, it seems that the output of --platform_status and qemu hmp "info sev" is decimal, but the --calc_measurement requires ascii-encoded hex bytes? Should I convert it to hex?

**Comment by jpecholt** [comment]
As for the second question: yes, --platform_status returns decimal and --calc_measurement requires it in ascii-encoded hex format. I.e., if platform_status returns:
```
api_major:	0
api_minor:	17
...
build:		22
...
```
Then calc_measurement expects something like this:
```
#sevtool --calc_measurement context (always 04)   API Major   API Minor  Build    SEV policy           digest                       MNonce             TIK
sevtool --calc_measurement  04                    00          11         16      <SEV policy>  <sha256sum over OVMF.fd>   <Nonce from measurement>    <TIK>

**Comment by zeyu-zh** [comment]
> As for the second question: yes, --platform_status returns decimal and --calc_measurement requires it in ascii-encoded hex format. I.e., if platform_status returns:
> 
> ```
> api_major:	0
> api_minor:	17
> ...
> build:		22
> ...
> ```
> 
> Then calc_measurement expects something like this:
> 
> ```
> #sevtool --calc_measurement context (always 04)   API Major   API Minor  Build    SEV policy           digest                       MNonce             TIK
> sevtool --calc_measurement  04                    00          11         16      <SEV policy>  <sha256sum over OVMF.fd>   <Nonce from measurement>    <TIK> 
> ```

Thanks! Their design is very interesting.

**Comment by zeyu-zh** [comment]
I have got the right measurement by using sha256 for OVMF. But I'm still very confused about the README, "The digest parameter is the SHA256 (Naples) or SHA384 (Rome) output digest of the data passed into LaunchUpdateData and LaunchUpdateVMSA".

**Comment by zeyu-zh** [comment]
@jpecholt Thanks!

**Comment by jpecholt** [comment]
Ah yes, my example applies to the first generation of SEV, meaning it uses SHA256 to calculate the launch measure. And I assume what is meant here is that anything that is passed to the SEV Firmware via the API calls LAUNCH_UPDATE_DATA and LAUNCH_UPDATE_VMSA (see the [SEV API](https://developer.amd.com/wp-content/resources/55766.PDF) for example) is part of the measurement. For SEV-ES (which concerns the latter command) I am less experienced so I can't comment too much. Luckily, in the case of SEV, this only encompasses the OVMF binary which is passed the the firmware by QEMU/the kernel using the LAUNCH_UPDATE_DATA command if I'm not mistaken.

**Comment by zeyu-zh** [comment]
@jpecholt Someone corrected the README, I'll close this issue. Thanks!
https://github.com/AMDESE/sev-tool/commit/07fcf57f4991585d0a08475351b74a501718c48f
