### ISSUE TITLE
Correct id of loader element in find_sev_ovmf_bin

### ISSUE THREAD

**Issue by rrkapitz** [AMDESE/sev-tool#45]
Hi, 

the function  `std::string SEVDevice::find_sev_ovmf_bin(char *capabilities)` seems to match on the first element tag of the xml data provided by capabilites. Here it looks like we want to match on the second element tag to get the loader binary (cf. https://libvirt.org/formatdomaincaps.html#elementsOSBIOS).  Adding the following lines does the job on my side and ./sevtool --verbose  --sys_info  works now.

Ciao,
   Rüdiger 

---- 
 ```
std::string SEVDevice::find_sev_ovmf_bin(char *capabilities)
 {
-    char *ovmf_bin_loc = (char *) malloc(strlen(capabilities));
-    strncpy(ovmf_bin_loc, capabilities, strlen(capabilities));
+    char *ovmf_loader_loc = (char *) malloc(strlen(capabilities));
+    strncpy(ovmf_loader_loc, capabilities, strlen(capabilities));
+    char *p_loader_start= strstr(ovmf_loader_loc, "<loader ");
+
+    char *ovmf_bin_loc = (char *) malloc(strlen(p_loader_start));
+    strncpy(ovmf_bin_loc, p_loader_start, strlen(p_loader_start));
 
     char *p_val_end = strstr(ovmf_bin_loc, "</value>");
```

**Comment by larrydewey** [comment]
Should be resolved in #54 when merged upstream. Instead of looking to patch this legacy code which tests the preparation of the host, it makes sense just to remove it.
