### ISSUE TITLE
openssl symbol RSA_get0_n & RSA_get0_e not found

### ISSUE THREAD

**Issue by Ruide** [AMDESE/sev-tool#46]
sevcert.cpp: In member function ‘SEV_ERROR_CODE SEVCert::decompile_public_key_into_certificate(sev_cert*, EVP_PKEY*)’:
sevcert.cpp:828:45: error: ‘RSA_get0_e’ was not declared in this scope
             exponent = RSA_get0_e(rsa_pubkey);   // Exponent
                                             ^
sevcert.cpp:829:44: error: ‘RSA_get0_n’ was not declared in this scope
             modulus = RSA_get0_n(rsa_pubkey);    // Modulus

I guess openssl v1.1.1 or greater is needed.

**Comment by lilienbm** [comment]
Hi,

What version of OpenSSL are you using? The tool was built for OpenSSL 1. I
assume you're running 3, which changed the way RSA is handled?

**Comment by Ruide** [comment]
I checked with openssl 1.1.0x and they do not have this symbol. While 1.1.1x do have this symbol. Thank you for your quick response!

**Comment by larrydewey** [comment]
It sounds like this issue has been resolved. I will close this now, but feel free to re-open if there are further concerns which have been left unresolved.
