### ISSUE TITLE
export_cert_chain_vcek -- why query kdsintf at the  Platform Owner side for ARK?

### ISSUE THREAD

**Issue by rrkapitz** [AMDESE/sev-tool#49]
Hi, when going through the description of the export_cert_chain_vcek input flag I was wondering why the kdsintf is queried on the side of the Platform Owner for the ASK and ARK. Later the collected information is used on the Guest Owner side by the input flag validate_cert_chain_vcek. 

Thus, I could create an alternative chain on the Platform Owner side since the ARK is self-signed? (Desc. says: Validates the ARK using the ARK (self-signed)). 

I would have expected to query the VCEK and the ASK as part of export_cert_chain_vcek and then as part of  validate_cert_chain_vcek collect the  ARK. This way I can use the ARK to check the ASK and the VCEK?

**Comment by larrydewey** [comment]
@rrkapitz it sounds like @lilienbm was able to answer your question? Feel free to re-open if this needs additional follow-up.
