### ISSUE TITLE
The `snp_attestation_report` struct seems to be out of date from the documentation

### ISSUE THREAD

**Issue by rjzak** [AMDESE/sev-tool#51]
Page 45 of the SEV documentation https://www.amd.com/system/files/TechDocs/56860.pdf shows additional fields which conflict with the `reserved4` field. The additional fields in the document are `COMMITTED_TCB`, `CURRENT_BUILD`, `CURRENT_MINOR`, `CURRENT_MAJOR`, `COMMITTED_BUILD`, `COMMITTED_MINOR`, `COMMITTED_MAJOR`, `LAUNCH_TCB`.

Code: https://github.com/AMDESE/sev-tool/blob/master/src/rmp.h#L334

**Comment by larrydewey** [comment]
@rjzak #56 should update the structure to match the 1.51 specification.

**Comment by larrydewey** [comment]
@rjzak changes have been merged. Thanks again, and let us know if you find any other inconsistencies.
