### ISSUE TITLE
sevtool --export_cert_chain_vcek     reports error

### ISSUE THREAD

**Issue by niteeshkd** [AMDESE/sev-tool#52]
I notice the following when I execute 'sudo sevtool --ofolder ~/po/test2 --export_cert_chain_vcek 0200000000000693' where 0200000000000693 is the TCB reported from the attestation report of a SNP guest.
-----------------------------
0, blSPL=02
1, teeSPL=00
2, reserved0SPL=00
3, reserved1SPL=00
4, reserved2SPL=00
5, reserved3SPL=00
6, snpSPL=06
7, ucodeSPL=93
...
csplit: /usr/psp-sev-assets/cert_chain-00: No such file or directory
Error: renaming vcek cert chain file

Command Unsuccessful: 0x15
-----------------------------

But, it does create the files cert_chain.pem and  vcek.der .

**Comment by niteeshkd** [comment]
It seems it required the presence of the directory /usr/psp-sev-assets . After creating this directory manually, 'sudo sevtool --ofolder ~/po/test2 --export_cert_chain_vcek 0200000000000693' runs fine.

**Comment by larrydewey** [comment]
Thanks @niteeshkd. I will look into this.

**Comment by larrydewey** [comment]
This should be resolved now that #55 is merged.
