### ISSUE TITLE
Running the pek_cert_import command reports 'Command Unsuccessful'

### ISSUE THREAD

**Issue by hyggy2019** [AMDESE/sev-tool#53]
#./sevtool --pek_cert_import    pek_csr.signed.cert   oca.cert 
Command Unsuccessful: 0x06

Any tips?

**Comment by hyggy2019** [comment]
p.s., I'm running sevtool on a Milan platform (AMD EPYC 7513). 
Maybe sevtool don't support Milan Platform?

**Comment by hyggy2019** [comment]
> 
Thanks for your reply. However in the readme.md, it reads 
_7. pek_cert_import
     - This command imports a signed PEK CSR together with the corresponding OCA certificate. Import will not be successful if the platform is not self-owned at this stage.
     - Required input args:
         - The signed PEK CSR
         - The OCA certificate that signed the CSR (in AMD certificate format)
     - Files read in: [signed PEK CSR] [oca_cert_file]
     - Outputs: none
     - Platform/Guest Owner: Platform Owner
     - Example
         ```sh
         $ sudo ./sevtool --pek_cert_import pek_csr.signed.cert oca.cert_

I've tried again as follows. It seemed  'pek_cert_import command'  still in trouble. 
# ./sevtool --set_self_owned 
Command Successful

# ./sevtool --pek_cert_import    pek_csr.signed.cert    oca.cert 
**Command Unsuccessful: 0x01**

# ./sevtool --platform_status
api_major:      1
api_minor:      42
platform_state: 2
**owner:          0**
config:         1
build:          42
guest_count:    1


# ls -l
total 2736
-rw-r--r--. 1 root root    1600 Mar 10 04:22 ark.cert
-rw-r--r--. 1 root root    3200 Mar 22  2021 ask_ark.cert
-rw-r--r--. 1 root root    1600 Mar 10 04:22 ask.cert
-rw-r--r--. 1 root root    2084 Mar 10 04:04 cek.cert
-rw-r--r--. 1 root root    6252 Mar 10 04:22 cert_chain.cert
-rw-r--r--. 1 root root   19304 Mar 10 04:22 cert_chain_readable.txt
-rw-r--r--. 1 root root    4679 Mar 10 04:22 certs_export.zip
-rw-------. 1 root root     288 Mar 10 04:15 ec384-key-pair.pem
-rw-r--r--. 1 root root     215 Mar 10 04:15 ec384pub.pem
-rw-r--r--. 1 root root    2084 Mar 10 21:45 oca.cert
-rw-r--r--. 1 root root    2084 Mar 10 04:22 pdh.cert
-rw-r--r--. 1 root root    6411 Mar 10 04:22 pdh_readable.txt
-rw-r--r--. 1 root root    2084 Mar 10 04:22 pek.cert
-rw-r--r--. 1 root root    2084 Mar 10 21:44 pek_csr.cert
-rw-r--r--. 1 root root    6411 Mar 10 21:44 pek_csr_readable.txt
-rw-r--r--. 1 root root    2084 Mar 10 21:45 pek_csr.signed.cert
-rwxr-xr-x. 1 root root 2701464 Mar 10 21:56 sevtool

**Comment by lilienbm** [comment]
Ahh, so PEK_CERT_IMPORT has a requirement that it only works in the INIT
platform state. If you are running a guest (guest_count: 1, the platform
state is RUNNING. Try shutting down the guest and try again.

**Comment by hyggy2019** [comment]
> 

It works. Thanks a lot!
