### ISSUE TITLE
readme: deps-install.sh errors on ubuntu 20.04

### ISSUE THREAD

**Issue by osresearch** [AMDESE/sev-tool#63]
Running `deps-install.sh` as instructed in the `readme.md` causes errors on Ubuntu 20.04:

```
# sh ./deps-install.sh 
sed: -e expression #1, char 14: Invalid range end
./deps-install.sh: 109: [: -lt: unexpected operator
```

The `sed` command error is because the `-` should be the first option in the range, although that leaves the `"` characters from the file:

```
# grep VERSION_ID= /etc/os-release 
VERSION_ID="20.04"
```

A simpler command might be:

```
-- a/deps-install.sh
+++ b/deps-install.sh
@@ -101,7 +101,7 @@ find_distribution_details()
 
 older_than_bionic()
 {
-       VERSION_NUMBER=$(cat /etc/os-release | grep 'VERSION_ID=' | sed s%[a-z\_\-\=]%%ig)
+       VERSION_NUMBER=$(cat /etc/os-release | grep 'VERSION_ID=' | sed s%[^0-9]%%ig)
        IS_OLDER=0
 
        debug $LINENO ":" "VERSION_NUMBER => ${VERSION_NUMBER}"
```

**Comment by larrydewey** [comment]
That is definitely an issue. Thanks for bringing it up @osresearch!

**Comment by larrydewey** [comment]
I merged the fixes, so this _should_ be fixed. Feel free to re-open if you run into any additional issues.
