### ISSUE TITLE
SEV failed to INIT error 0x13

### ISSUE THREAD

**Issue by osresearch** [AMDESE/sev-tool#65]
I'm running into a similar error to #6 on ubuntu 20.04 running on a Supermicro H12SST-PS with AMD 7313, AMI BIOS 2.1, and an upgraded `amd_sev_fam19h_model0xh_1.33.03.sbin` in `/lib/firmware/amd/` plus `mem_encrypt=on kvm_amd.sev=1` on the kernel command line.

```
[   25.414226] ccp 0000:45:00.1: no command queues available
[   25.414228] ccp 0000:45:00.1: ccp initialization failed
[   25.414815] ccp 0000:45:00.1: psp enabled
[   25.429516] ccp 0000:45:00.1: SEV: failed to INIT error 0x13
```

`sev-tool` reports:
```
# ./src/sevtool  --platform_status
api_major:	1
api_minor:	28
platform_state:	0
owner:		0
config:		0
build:		28
guest_count:	0
```
```
# ./src/sevtool  --verbose --sys_info
cat: ../.git/refs/heads/master: No such file or directory
-------------------------System Info-------------------------
Hostname: quick-serval
BIOS Version: 2.1
BIOS Release Date: 05/07/2021
SMT/Multi-Threading Status Per Socket: 
CPU(s):                          32
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Processor Frequency (all sockets): 
3000 MHz
Operating System: "Ubuntu 20.04 LTS"
Kernel Version: 5.4.0-117-generic
Git Commit #: Firmware Version: API_Major: 0, API_Minor: 0, BuildID: 0
Platform Family 19, Model 01
```

Since the `readme.md` says the command was renamed from `platform_reset`, I've run `sevtool --factory_reset`. Unfortunately it doesn't fix it, although it does say "`Command Successful`".

**Comment by larrydewey** [comment]
Can you verify that the SEV features have been enabled in the BIOS?

**Comment by larrydewey** [comment]
@osresearch Once you have performed the update, the BIOS features that are needed for SNP enablement are exposed in two places:

1. Under "Advanced Menu" -> CPU Configuration. You will find the SMEE, SEV ASID Count, SEV-ES ASID Space Limit Control, & SNP Memory (RMP Table) Coverage knobs.
2. Under the Advanced Menu -> NB Configuration, you will find the SEV-SNP Support knob

**Comment by Villain88** [comment]
Hi, i have a similar problem. I am using SuperMicro H12SSL-i motherboard and AMD EPYC 7343 processor.
Latest BIOS version 2.3 from 10/20/2021.
kernel: 5.14.0-rc2-snp-host-6d4469b86f90
latest firmware: amd_sev_fam19h_model0xh_1.33.03

I get errors in dmesg:

> [    0.573429] SEV-SNP: Memory for the RMP table has not been reserved by BIOS
> ....
> [    5.485103] ccp 0000:49:00.1: SEV: failed to INIT error 0x13

> # cat /sys/module/kvm_amd/parameters/sev_snp 
> N


No RMP settings in bios, but SEV-SNP setting is enabled.

What could be the way out?

P.S.: on _rmmpd ccp_ or _reboot_ I getting kernel panic

**Comment by Villain88** [comment]
@larrydewey What about TSME. Should it be enabled or disabled?

**Comment by larrydewey** [comment]
@Villain88 TSME should be an optional flag, but it is worth trying to see if there is something acting erratically. Will you take a screen shot of the menu screen of CPU configuration and NB configuration under Advanced? That us narrow down the possibilities.

**Comment by larrydewey** [comment]
@Villain88 After talking with an FAE, it looks like BIOS version 2.4 for your SuperMicro H12SSL-i is still under active development, and the feature-set for SEV-SNP will be included in that BIOS update.

**Comment by Villain88** [comment]
> @Villain88 After talking with an FAE, it looks like BIOS version 2.4 for your SuperMicro H12SSL-i is still under active development, and the feature-set for SEV-SNP will be included in that BIOS update.

thanks, I found out from the manufacturer, but so far there are no updates, I'm waiting

**Comment by osresearch** [comment]
Supermicro [firmware 2.4 for the H12SST](https://www.supermicro.com/support/resources/bios_ipmi.php?vendor=2) (and several others) was just released with [the SNP support mentioned in the notes](https://www.supermicro.com/Bios/softfiles/15437/H12SST-PS_BIOS_2.4_release_notes.pdf)

> Added setup item, "SNP Memory (RMP Table) Coverage" and "Amount of Memory to Cover" in CPU Configuration Page.

There are some warnings in the release notes about CPLD for updating from pre-2.x versions:

> 3) BIOS R 2.x requires the latest motherboard CPLD before updating. If you purchased the system before 3/13/2021, please contact Supermicro Technical Support to verify before updating the BIOS.

I'll download it and give it a try later this week.

**Comment by Villain88** [comment]
Thank you, after updating the bios to 2.4 the error is gone

**Comment by Villain88** [comment]
> Aweseome. @Villain88 and @osresearch, it sounds like the issue has been resolved?

I think so thanks for the help

**Comment by osresearch** [comment]
I've updated the Supermicro HS12 to 2.4 with support enabled in the UEFI setup ("`Auto`" does not work; I had to explicitly turn it on). `dmesg` now has a different error:

```
[   26.032498] ccp 0000:43:00.1: enabling device (0000 -> 0002)
[   26.033381] ccp 0000:43:00.1: no command queues available
[   26.033382] ccp 0000:43:00.1: ccp initialization failed
[   26.033944] ccp 0000:43:00.1: psp enabled
[   26.244092] ccp 0000:43:00.1: SEV API:1.49 build:6
[   26.452783] kvm: Nested Virtualization enabled
[   26.452980] SVM: SEV supported
[   26.453005] kvm: Nested Paging enabled
[   26.453005] SVM: Virtual VMLOAD VMSAVE supported
```

Is "`no command queues available`" and "`ccp initialization failed`" fatal? It does go on to initialize the PSP and reports that SEV is supported.

**Comment by lzadjsf** [comment]
Hi folks!

I've just found required file.

https://download.amd.com/developer/eula/sev/amd_sev_fam19h_model0xh_1.54.01.zip


Also reference page here: https://www.amd.com/en/developer/sev.html
