### ISSUE TITLE
Incompatible version of OpenSSL found

### ISSUE THREAD

**Issue by neverovsky** [AMDESE/sev-tool#71]
sev tool doesn't compile on Ubuntu 22.04 because version is too new?

Check that OpenSSL is >= 1.1.0 by looking for version specific APIs

autoreconf -vif && ./configure && make
checking for library containing EVP_PKEY_base_id... no
configure: error: Incompatible version of OpenSSL found

but current installed openssl version:
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by larrydewey** [comment]
@neverovsky I merged in a change for `configure.ac` which will provide a temporary work-around for OpenSSL 3.0.x. I will still need to research the upgrade path for 3.x and make sure any of the newer libraries don't break expected behavior.

**Comment by neverovsky** [comment]
@larrydewey yes it works ! thank you

**Comment by neverovsky** [comment]
closing

**Comment by larrydewey** [comment]
As an update, adding the adjustment to `configure.ac` does bypass the compiler, but as RSA is handled differently in 3.x, there will need to be some significant changes, as it breaks expected behavior.
