### ISSUE TITLE
How to attest the platform owner in SEV-SNP?

### ISSUE THREAD

**Issue by cowbon** [AMDESE/sev-tool#73]
Unlike `export_cert_chain`, `export_cert_chain_vcek` contains only ASK, ARK and VCEK. Even through guest owners may longer need to trust the platform, may I ask if there's any way to demonstrate that the platform is provided by a specific platform owner cryptographically in SEV-SNP?. In SEV, we have PEK signed by both ASK from AMD and OCA by the platform owner, but I can't find PEK, PDH and guest owner generated DH and session buffer from SEV-SNP.

**Comment by larrydewey** [comment]
@cowbon Great question! The [HOST_DATA field](https://www.amd.com/system/files/TechDocs/56860.pdf#page=44) described in table 21 may be utilized by the Host to provide an unique arbitrary value which is included in the attestation report. As it is inclued in the report, that field is also included in the Attestation Report's measurement.

**Comment by larrydewey** [comment]
@cowbon I am closing this due to the lack of activity. Feel free to re-open if you have comments/questions.
