### ISSUE TITLE
How to use certificate chain for attestation

### ISSUE THREAD

**Issue by shuk777** [AMDESE/sev-tool#75]
Hi, there.

I want to use certificate chain for attestation using [simple-kbs](https://github.com/confidential-containers/simple-kbs). It takes a string as input and I'm not sure about how to convert these cert files into a string. Can I just copy/paste them into one file?

Best regards

**Comment by larrydewey** [comment]
Would you mind clarifying what you are looking for? From my understanding, [simple-kbs](https://github.com/confidential-containers/simple-kbs) is a stand-alone GRPC service, which performs the attestation within the service.
