### ISSUE TITLE
Commands IDs are inconsistent

### ISSUE THREAD

**Issue by Daviiap** [AMDESE/sev-tool#82]
In the API spec, the Table 13 provides the IDs of the API commands, but in the code, the commands IDs are different.

For example, the PLATFORM_STATUS command, in the api has ID 0x04, but in the sev-tool, the ID is 0x01.

What´s the reason of this difference?

**Comment by larrydewey** [comment]
[Table 13](https://www.amd.com/system/files/TechDocs/55766_SEV-KM_API_Specification.pdf#page=37) of the API Specification describes the Command IDs for the PSP. The Userspace API features exposed by the kernel are mapped differently (see [uapi/linux/psp.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/psp-sev.h#L21)).
