### ISSUE TITLE
Not able to setup the tool properly.

### ISSUE THREAD

**Issue by hiteshvpatel256** [AMDESE/sev-tool#83]
Hi

When trying to install the tool, it generates the binary for sevtool inside "/sev-tool/src" package.

As of now GCP N2D instance is setup for dev purpose.
Below is the actual output for particular command with flag with executing generated binaries.
```
`$ sudo ./sevtool --platform_status
terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't open /dev/sev!

Aborted`
```

I am beginner for sev(enclave based TEE) technology.

Any help about why the tools is not giving platform status.

Thanks

**Comment by larrydewey** [comment]
@hiteshvpatel256 the error you posted is stating that the device driver is not loaded. Are you trying to run this from within a guest vm on GCP, or are you running this on a Host Node?
