### ISSUE TITLE
How to calculate the correct GTCX.LD?

### ISSUE THREAD

**Issue by Bonjourz** [AMDESE/sev-tool#9]
The guest owner should verify whether the image is launched correctly during the boot:
`10. Run the calc_measurement command and verify the measurement from the Platform owner matches what you calculated/expected`

And the measurement can be calculated from the Digest. But how can we get the correct Digest? Can you provide more details about the digest context algorithm the firmware use?

**Comment by lilienbm** [comment]
Hello,

I recommend calling init during LaunchStart time
    SHA256_Init(&mLaunchDigest);
Then calling update during LaunchUpdateData and LaunchUpdateVMSA
    SHA256_Update(&mLaunchDigest, Data.Addr(), Data.Size());
Then call final during LaunchMeasure to pass into the hmac calculations
    SHA256_Final(Digest, &mLaunchDigest);

Here is how I initialized it
    SHA256_CTX mLaunchDigest;

**Comment by Bonjourz** [comment]
> Hello,
> 
> I recommend calling init during LaunchStart time
> SHA256_Init(&mLaunchDigest);
> Then calling update during LaunchUpdateData and LaunchUpdateVMSA
> SHA256_Update(&mLaunchDigest, Data.Addr(), Data.Size());
> Then call final during LaunchMeasure to pass into the hmac calculations
> SHA256_Final(Digest, &mLaunchDigest);
> 
> Here is how I initialized it
> SHA256_CTX mLaunchDigest;

I get it. Thank you!

**Comment by lilienbm** [comment]
The hash is SHA256 for Naples and Rome

**Comment by alina-weber** [comment]
Could this issue please be explained in more detail. I tried to implement the explanation above and was able to calculate a digest but was not able to validate the measurement using this digest through the command `calc_measurement` of the sevtool so far. 
This was tested on an epyc2 processor and the used kernel is from the AMDSEV repo, branch sev-es, commit 7a8980deedb8469c3da46dfca71e00fd567b4bf6 (kernel version is 5.6.0-sev-es+). My implementation for the digest is visible in the file in [svm_c.zip](https://github.com/AMDESE/sev-tool/files/5607814/svm_c.zip) (I zipped it to be able to upload it). My added lines are detectable by `// Changes by Alina *(` written above and `// *)` below. As a result, the dmesg shows an ouput like the following:
![Screenshot from 2020-11-27 13-36-14](https://user-images.githubusercontent.com/44259717/100452368-4c2c8080-30b9-11eb-95bd-4e594a90cae0.png)


I tried to update the digest in `sev_launch_update_vmsa()` before and after TLB flush as well as before and after the execution of the command by the SP.

I also noticed that the parameter `build_id` of the sevtool command `calc_measurement` does not influence the measurement. As far as I remember, I sometimes calculated the same digest as used in the example of `calc_measurement`.

To verify the measurement I also extracted it via QMP-monitor with `{"execute":"query-sev-launch-mesure"}` and it was equal to the values in my dmesg output.
